/*
 * KubeSphere Advanced
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0.0
 * Contact: kubesphere@yunify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kubesphere.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** Workspace is the Schema for the workspaces API */
@ApiModel(description = "Workspace is the Schema for the workspaces API")
public class ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace {
  @SerializedName("apiVersion")
  private String apiVersion = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("metadata")
  private V1ObjectMeta metadata = null;

  @SerializedName("spec")
  private ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceSpec spec = null;

  @SerializedName("status")
  private ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus status = null;

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace apiVersion(
      String apiVersion) {
    this.apiVersion = apiVersion;
    return this;
  }

  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should
   * convert recognized schemas to the latest internal value, and may reject unrecognized values.
   * More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources
   *
   * @return apiVersion
   */
  @ApiModelProperty(
      value =
          "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources")
  public String getApiVersion() {
    return apiVersion;
  }

  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace kind(String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer
   * this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More
   * info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds
   *
   * @return kind
   */
  @ApiModelProperty(
      value =
          "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace metadata(
      V1ObjectMeta metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   *
   * @return metadata
   */
  @ApiModelProperty(value = "")
  public V1ObjectMeta getMetadata() {
    return metadata;
  }

  public void setMetadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
  }

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace spec(
      ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceSpec spec) {
    this.spec = spec;
    return this;
  }

  /**
   * Get spec
   *
   * @return spec
   */
  @ApiModelProperty(value = "")
  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceSpec getSpec() {
    return spec;
  }

  public void setSpec(ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceSpec spec) {
    this.spec = spec;
  }

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace status(
      ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   *
   * @return status
   */
  @ApiModelProperty(value = "")
  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus getStatus() {
    return status;
  }

  public void setStatus(
      ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus status) {
    this.status = status;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace
        comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace =
            (ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace) o;
    return Objects.equals(
            this.apiVersion,
            comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace.apiVersion)
        && Objects.equals(
            this.kind, comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace.kind)
        && Objects.equals(
            this.metadata, comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace.metadata)
        && Objects.equals(
            this.spec, comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace.spec)
        && Objects.equals(
            this.status, comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2Workspace {\n");

    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
