/*
 * KubeSphere Advanced
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0.0
 * Contact: kubesphere@yunify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kubesphere.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** DevOpsProjectStatus defines the observed state of DevOpsProject */
@ApiModel(description = "DevOpsProjectStatus defines the observed state of DevOpsProject")
public class ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectStatus {
  @SerializedName("phase")
  private String phase = null;

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectStatus phase(
      String phase) {
    this.phase = phase;
    return this;
  }

  /**
   * Phase is Status of DevOpsProject
   *
   * @return phase
   */
  @ApiModelProperty(value = "Phase is Status of DevOpsProject")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectStatus
        comGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectStatus =
            (ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectStatus) o;
    return Objects.equals(
        this.phase,
        comGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectStatus.phase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phase);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(
        "class ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectStatus {\n");

    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
