/*
 * KubeSphere Advanced
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0.0
 * Contact: kubesphere@yunify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kubesphere.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** DevOpsProjectSpec defines the desired state of DevOpsProject */
@ApiModel(description = "DevOpsProjectSpec defines the desired state of DevOpsProject")
public class ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec {
  @SerializedName("description")
  private String description = null;

  @SerializedName("displayName")
  private String displayName = null;

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec description(
      String description) {
    this.description = description;
    return this;
  }

  /**
   * Description is Description of DevOpsProject
   *
   * @return description
   */
  @ApiModelProperty(value = "Description is Description of DevOpsProject")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec displayName(
      String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * DisplayName is DisplayName of DevOpsProject
   *
   * @return displayName
   */
  @ApiModelProperty(value = "DisplayName is DisplayName of DevOpsProject")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec
        comGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec =
            (ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec) o;
    return Objects.equals(
            this.description,
            comGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec.description)
        && Objects.equals(
            this.displayName,
            comGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, displayName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append(
        "class ComGithubRunzexiaKubesphereCrdSamplePkgApisDevopsV1alpha2DevOpsProjectSpec {\n");

    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
