/*
 * KubeSphere Advanced
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0.0
 * Contact: kubesphere@yunify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kubesphere.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;

/** WorkspaceStatus defines the observed state of Workspace */
@ApiModel(description = "WorkspaceStatus defines the observed state of Workspace")
public class ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus {
  @SerializedName("phase")
  private String phase = null;

  public ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus phase(String phase) {
    this.phase = phase;
    return this;
  }

  /**
   * Phase is Status of Workspace
   *
   * @return phase
   */
  @ApiModelProperty(value = "Phase is Status of Workspace")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus
        comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus =
            (ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus) o;
    return Objects.equals(
        this.phase, comGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus.phase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phase);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComGithubRunzexiaKubesphereCrdSamplePkgApisIamV1alpha2WorkspaceStatus {\n");

    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
