/*
 * KubeSphere Advanced
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0.0
 * Contact: kubesphere@yunify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kubesphere.client.apis;

import io.kubesphere.client.ApiException;
import io.kubesphere.client.models.V1APIGroupList;
import org.junit.Ignore;
import org.junit.Test;

/** API tests for ApisApi */
@Ignore
public class ApisApiTest {

  private final ApisApi api = new ApisApi();

  /**
   * get available API versions
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getAPIVersionsTest() throws ApiException {
    V1APIGroupList response = api.getAPIVersions();

    // TODO: test validations
  }
}
