/*
 * KubeSphere Advanced
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2.0.0
 * Contact: kubesphere@yunify.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.kubesphere.client.apis;

import io.kubesphere.client.ApiException;
import io.kubesphere.client.models.V1APIGroup;
import org.junit.Ignore;
import org.junit.Test;

/** API tests for DevopsKubesphereIoApi */
@Ignore
public class DevopsKubesphereIoApiTest {

  private final DevopsKubesphereIoApi api = new DevopsKubesphereIoApi();

  /**
   * get information of a group
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getAPIGroupTest() throws ApiException {
    V1APIGroup response = api.getAPIGroup();

    // TODO: test validations
  }
}
